rmarkdown::render("schedule.Rmd")
rmarkdown::render("wk/wk01.Rmd")
rmarkdown::render("wk/wk02.Rmd")
rmarkdown::render("wk/wk03.Rmd")
rmarkdown::render("wk/wk04.Rmd")
rmarkdown::render("wk/wk05.Rmd")
rmarkdown::render("wk/wk06.Rmd")
