---
title: "Frequently Asked Questions"
output:
  pdf_document: default
  html_document: default
date: "Last Updated `r Sys.time()`"
---

_page in development_

Download this file as a [[PDF]](faq.pdf)

# Assignments

## How do I complete the assignments? 

Most homework assignments will come with a template to use. This will be a R markdown (`*.Rmd`) file for R users, and a Word document (`*.doc`) for SPSS users. 

R users write their code and answers directly into the Rmd file. SPSS users will copy their code and relevant output into the Word doc, along with writing their answers in the Word doc directly. 

All homework files must be compiled or converted to PDF before submission. R users `knit` their file to PDF, SPSS users will `save as` their Word document as PDF. 

Links to the templates can be found in the homework assignment itself. A list of all assignment files can be found on the [notes](notes.html) page. 
    
    
## How do I turn in Homework?

Unless explicitly stated otherwise, 

* It should be in PDF format. 
* The file should be clearly named using this format: `assignment_userid.pdf`. E.g. `univ_graphics_rdonatello.pdf`
* Uploaded to the corresponding assignment folder under **Incoming** in Google Drive. 
* Project assignments are also uploaded to BBL. See next section for reasoning. 

## What are you looking for when you grade? 

* Most assignments include examples directly in the assignment file itself. 
* Correct english grammer, spelling, formatting. 
* Concice, clear and complete answers. 
* Correct statistical methods used
* That you answered the question posed. 
* No extreneous output or code

**Standard Assignments**

Standard homework assignments just get checked off for completion. If it's complete full credit is awarded. 
I will review each assignment, write comments, corrections and suggestions for improvement on the PDF itself. I will put my copy into your personal returned folder. 

**Project Assignments**

These assignments are **also** uploaded to Blackboard Learn. This allows me to use a rubric for grading. Project assignments should be considered quality work and such refined, reviewed, and absolutely spellchecked before submission. 


## Why do we do peer review instead of just getting feedback from you? 

* Everyone has different thought processes and may have approached the question from a different perspective that can help you learn the material. 
* Co-authoring and reviewing your peers work is part of a professional research position. 
* Learning how to provide good feedback will make you a better collaborator
* This is a delayed version of paired programming - another set of eyeballs can typically help you find your mistake. 
* I have 10fold more assignments to review than you do. You'll get your peer's reviews back faster than I can get yours back.
* I will be looking for different things than your peers will be. This is a good thing. They are looking from "untrained eyes", which can be very critical to make sure you are explaining yourself clearly. I can better "figure out" what you are meaning to say  - they are the ones that will best tell you when/where you need to explain your findings better. 


## How do I conduct a Peer Review

1. Check the [Peer Review Rotation](https://docs.google.com/spreadsheets/d/1hjRLCwf-5lZNX-6jPs75WvtTOp3sKmuh10eiKfL6lm0/edit?usp=sharing) spreadsheet to see who you are scheduled to review. 
2. Download a copy of the assignment for each person you are to review. 
    - **Do not edit directly in Google Documents unless you make your own copy first.** This has resulted in lost work in the past. 
    - If one or more of your reviewees did not submit their assignment, randomly select a new person and review their work instead. 
3. Using either track changes in Word, or comment bubbles/annotation in Adobe, provide feedback to your peer. 
    - Be specific. Give the type of feedback that you want to recieve. 
    - Two positive comments about what they did well, or should continue to do.
    - Two corrections or suggestions for improvement. 
4. Save your edited versions with your username at the end of the file name after `revby` `assignment_authorid_revby_reviewerid.pdf`. E.g. If Kathy Gray were reviewing my assignment `univ_graphics_rdonatello.pdf`, her review file name would look like `univ_graphics_rdonatello_revby_kgray.pdf`
5. Upload your commented file to the top level **Reviewed** folder in our Google Drive. 
    - You do not have access to anyone elses folder except your own. 
    - I will move these into their author's folder after looking at your review. 


## Grading of peer reviews

I will go through the **Reviewed** folder and spot check for appropriate reviews. As I come across your reviews I will move them to their author's folder and assign you credit for the review in Blackboard. If I find your review is not providing quality feedback to the author you will not recieve credit for that review. 

----
----

# Statistical Programming Help 

## Where can I get help using R outside of class time? 

### Online
* Chico [R User Group](https://groups.google.com/forum/#!forum/chico-rug)
* UCLA IDRE [[R Learning modules]](https://stats.idre.ucla.edu/r/modules/)
* Our Slack Workspace

### In Person
* **Robin Donatello** - Stat professor. Holt 202
* **Edward Roualdes** - Stat professor. Holt 204 - eroualdes@csuchico.edu
* **Community Coding** Tutor Schedule TBD
* **Math Learning Lab (MLIB 4th floor)** Tutor Schedule TBD
    
    
### Helpful R code snippits

_not functional as of 8/22/18_

Here is a collection of helpful R [code snippits](snippits.html) for plotting, subsetting, handling missing values and so forth. Think of it as a FAQ for R code. 


## Where can I get help using SPSS outside of class time? 

### Online
* UCLA IDRE [[learning modules]](https://stats.idre.ucla.edu/spss/modules/)
* Sigma Plus SPSS [Tutorials](https://www.spss-tutorials.com/basics/)
* IBM Knowledge [[Center]](https://www.ibm.com/support/knowledgecenter/en/SSLVMB_24.0.0/statistics_spsstut_project_ddita-gentopic1.html)


## Other resources pending organization

* http://www.wesleyan.edu/qac/curriculum/resources/syntax.html
* PDS bookdown https://alanarnholt.github.io/PDS-Bookdown2/ 
* sjPlot vignette - custom plot appearance: https://cran.r-project.org/web/packages/sjPlot/vignettes/custplot.html 
