---
title: "Math 615 homepage"
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
wk1.date <- as.Date("2019-08-26")
```

This is the landing page for <span style="color:blue">**Statistical Methods for Graduate Research**</span> course taught by [Dr. Robin Donatello](http://www.norcalbiostat.com) for <span style="color:blue">**Fall 2019**</span>.   
This page is used for posting of regular announcements and information for students of the class. 


<!----

### 12/xx/18 - Final Exam. 10-12noon. Holt 155

<span style="color:red">**Office Hours for Finals Week**</span> 

* Tuesday 2-4pm, Holt 155

<span style="color:red">**Allowed Exam Materials**</span> 

* The [[OFFICIAL]](https://norcalbiostat.github.io/MATH615/FinalDocs/FinalExam_Fall17_Supplemental.pdf) supplemental information and analyses for the Outlook on Life Survey. 
    - Print these pages. Ensure that you understand what models are being fit and how to read the output. You are allowed to write notes on these pages.
    - Be prepared to answer questions about modeling and interpreting these analyses. 
* Paper on [Smoking Behavior of US Youth](FinalDocs/Smoking behavior child welfare - Fettes 2011.pdf).
    - Print, read, comment on, and bring to the final. 
    - Be prepared to answer questions about the methods, models, and results.
* A calculator
* Up to 2 pages of additional notes (does not include your notes on the supplemental output)

    
Additional information on this new survey, such as full wording of the question on how the variables were coded can be found in the [[codebook]](https://norcalbiostat.github.io/MATH615/FinalDocs/OOL%20Codebook.pdf) and [[survey questionnaire]](https://norcalbiostat.github.io/MATH615/FinalDocs/OOL%20Questionnaire.pdf). **Do not bring these to the final**. They are for you to use as reference material while you are learning to understand this survey.   

<span style="color:red">**Review List**</span> 
This final exam is comprehensive in that everything in this class builds upon previous topics. 
Here are a list of topics to review. All topics have equal importance, regardless of the time that was spent on each topic during class. 

* Probability
* Creating and interpreting confidence intervals
* Assumptions for statistical methods to be valid
* Generalizability, representativeness, bias, sampling frame
* Statistical Analysis Procedures: 
    - Two-sample T-tests for means and proportions
    - ANOVA and $\chi^{2}$ for multiple samples
    - Linear and Logistic regression.
* Identifying confounders, moderators and covariates. 
* Interpreting regression coefficients and making predictions using models. 
    - from linear and logistic models
    - using continuous and categorical variables



### 12/10/18 - Week 15

* Poster building week! See the project page for instructions. 
    - Drafts are due Thu 11/13, Peer review on Sat 12/15
    - Final version due (as printed) on Wed 12/19
* Take Home Final exam 
    - Handed out Wed 12/12 (Estimated) - no later than Friday 12/14. 
    - Due Friday 12/21
* **Office Hours**
    - Victoria (Poster design): 
      * Tue 10-10:45 MLIB Math tutor lab (4th floor)
      * Thu 12:45-1:45 Holt 155  
    - Me (Holt 202)
      * Mon 12/10 3-4pm
      * Tue 12/11 2-4pm - Community Coding (MLIB 442)
      * Wed 12/12 1-3pm
      * Thu 12/13 10-11am
      * Tue 12/18 2-3pm
      * Wed 12/19 10-11am
      * Thu 12/20 1-2pm
      
    

### 12/3/18 - Week 14
* You should be working on finishing the regression assignment, and Poster Prep Stage III this week. 
* You will be building models, and having to decide which model fits the data best using different criteria. 
    
### 11/26/18 - [Week 13](https://norcalbiostat.github.io/MATH615/wk/wk13.html)
<span style="color:red">**Summary of schedule updates**</span>   

* MLR assignment has been re-drafted and cut down significantly
* Poster prep stage III will not have a peer review
* Final we be take home, poster presentations will occur during the 2 hour final period. 

This week, let's ease back into things. Try to come back to "normal", when life is anything but normal.  

* Tuesday - Section review, recap, reorient
* Thursday - Logistic regression


### 11/19/18 - Fall Break. 
* Don't think about school, assignments or anything. 
* Please take some time to be among your family and practice self care in this incredibly stressful time. 

--->

### `r format(wk1.date+7*11, "%m-%d-%Y")` Week 12: Multivariable Regression Modeling

* Writing and interpreting multivariable models
* How else can tertiary variable muck up an observed bivariate relationship? Confounding. 
* Start HW10 this week. 


### `r format(wk1.date+7*10, "%m-%d-%Y")` Week 11: Moderation

Let's start to explore how a third variable can effect, or change, a pattern or relationship between two variables. This is called *moderation*, and it introduces a type of analysis called *stratification*. 

We're also going to continue your personal resarch by applying appropriate statistical analyses to your poster prep slides. (Stage III)

### `r format(wk1.date+7*9, "%m-%d-%Y")` Week 10: Correlation and Regression Analysis

* Two ways to assess relationships between two continuous measurements: 
    - Correlation. Is X associated with y?
    - Regression. How much does Y change as X changes? 
    
* Back to reading PMA5. The Applied Stats course notes is the short version. Quiz topics will be out of both. 




### `r format(wk1.date+7*8, "%m-%d-%Y")` Week 9: Inference on multiple groups

The [[Applied Stats]](https://norcalbiostat.github.io/AppliedStatistics_notes/) notebook is being updated to include separate sections for each bivariate analysis. Read through the relevant chapters prior to class. 

* Some board work on ANOVA on Tuesday
* Chi-squared activity with M&M's on Thursday

Each day will have open work time. 


---

### `r format(wk1.date+7*7, "%m-%d-%Y")` Week 8: Statistical Inference

* Active discussion on transformations for normality, and choosing appropriate analyses on Tuesday.
    - Bring your textbook!
* Start Bivariate Inference (hw08) on Thursday.
    - Two sample T-test for a difference in means. 


### `r format(wk1.date+6*7, "%m-%d-%Y")` Week 7: Quantifying Uncertainty, Calculating Probabilities

As we start our next phase of the class working on conducting _Inferential Statistics_, we need to finish learning how to correctly interpret a confidence interval, and how to use known distributions (like the sampling distribution) to calculate probabilities.  

Each day for the next 2 weeks we will cover how to analyze a different combination of response & explanatory variables. Don't wait until the end to do that portion of the HW08. As soon as we cover that topic, do that piece of the HW. 

This week you should also be working on your Poster prep stage II: Showcase your data.  

We're still working out of external resources such as 

* [OpenIntro Statistics textbook Ch5](https://leanpub.com/openintro-statistics)
* Dr. D's [Math 315 course notes](https://norcalbiostat.github.io/MATH315/reading/RAD_course_notes_f19.pdf) 


**Tuesday**  

* Calculating Probabilities under a known distribution [[Hack MD Lec05]](https://hackmd.io/@norcalbiostat/math615_lec05). 
* Additional resource for calculating probabilities
    - [Dr D's course notes ch 3.3](https://www.youtube.com/watch?v=Bv9iY8-UzYw&feature=youtu.be)
    - OpenIntro Statistis [Shiny app](https://gallery.shinyapps.io/dist_calc/)
* Interpreting Confidence intervals as a range of plausible values  
    - Collaborative recap on [[Hack MD Lec06]](https://hackmd.io/@norcalbiostat/math615_lec06) notes on terminology

    
**Thursday**

* Group quiz on interval estimation
* Foundations for how to conduct a thourough hypothesis test.   

---

### `r format(wk1.date+5*7, "%m-%d-%Y")` Week 6: Probability

So far you have been conducting an exploratory data analysis to learn the distributions of your measures, and to assess for any possible relationships in your research. You cannot make any statistical claims about whether or not a relationship is significant at this point. That is under the realm of _inferential statistics_ and will be the topic of the class after Spring break. 

To understand why inferential statistics can be used to make valid claims, we have to learn a little bit about _Probability_ first. If you are rusty on your basic statistics and probability, I recommend getting the OpenIntro textbook as a review. 

This is a much more mathematical section of the course, so be sure to plan your time accordingly. 

**Updates** I have cxl'd HW 6 (research proposal). 

---

### `r format(wk1.date+4*7, "%m-%d-%Y")` Week 5: Describing Relationships between two variables

Goals for the week: 

1. Describe the relationship between two variables using all the same descriptive principles you learned to describe a single variable. (HW05, HackMD lecture notes 04)
2. Start your research poster prep slides. (PPI)

**Housekeeping**

* Monday 2pm OH cancelled this week. Extra OH Monday at 9, and Wed at 9am.
* I will be out of town Wed aft - Sunday. I'll be reachable by Slack still, but mostly not at a computer. Kathy Gray will be covering class on Thursday, which will be mostly an open work day. 


----

### `r format(wk1.date+3*7, "%m-%d-%Y")` Week 4: Describing Distributions of Data

I'm alive!

> OH Cancelled Monday. Sorry, lot of Drs appts in the upcoming weeks that were scheduled months ago. 
> Additional OH Wednesday at 9am

If there's one take home message for this week, is to describe the distribution of variables you need: 

1. a picture
2. summary statistics
3. a complete sentence interpretation

> Re: Homework 03. I will adjusted the grading rubric to downweight the data management portion. 
> We'll continue to work more on data management this week (and for the next few weeks).



---

### `r format(wk1.date+2*7, "%m-%d-%Y")` Week 3: Preparing your data for analysis.

We talked about what a reproducible research pipeline looked like, and started a data management file that imported your research data into your SPC. 

This week we'll talk about how to identify features of data that will need to be changed prior to analysis. We can't cover them all, nor would you remember them all. This is a place where experience and repetition will be the true learning method. Most importantly, when you figure out how to do a "thing".. share that "thing" with others by posting the problem & code solution on the collaborative HackMD notes. You'll thank not only yourself but others later when you come across having to do that "thing" again.. (because it's never just once.) 

----


### `r format(wk1.date+7, "%m-%d-%Y")`: Week 2

Hope everyone had a relaxing 3day weekend. Office hours have been set. Thank you for contributing! 

* Monday 2-3pm Holt 202
* Tuesday 10-11am Holt  202
* Wednesday 2-4pm PHSC 213 (Community Coding)
* Thursday 2-4pm MLIB 442 (Community Coding)

Collaborative Hack MD notes are posted under "Materials" in the nav bar. 

Next up is formulating research hypotheses on your selected data, and setting up a reproducible research pipeline to prepare data for analysis. 

----

### `r format(wk1.date, "%m-%d-%Y")`: Welcome to Fall 19!

* This course website contains all materials except the textbook for this class. Be sure to familarize yourself with the organization. You will be here a lot. Bookmark this page.
* Specifically click on and explore items in the top navigation bar. 
* Take this survey to help choose when I should hold Office Hours: https://forms.gle/6ZTSfrJ2WbyKMfk39 
* We will use Slack to faciliate outside of class discussion, and to replace emails. 
    - Use the link under 'Tools' in the navigation boar of this page to go to our Slack workspace, make an account using your @mail.csuchico.edu email address. 
    - You must download either the desktop app, or the phone app, or both. Do not rely on the browser based version. 

