---
output:
  html_document:
    highlight: tango
    theme: flatly
css: ../css/customh5.css
---

```{r, message=FALSE, warning=FALSE, echo=FALSE}
library(stringr); library(dplyr)
library(knitr); library(kableExtra)

lec <- data.frame(filenames = paste0('lecture', list.files("lecture", pattern='*.pdf|*.html')))
read <- data.frame(filenames = paste0('reading', list.files("reading", pattern='*.pdf|*.html')))
hw <- data.frame(filenames = paste0('hw', list.files("hw", pattern='*.pdf|*.html')))


out.lec <- lec %>% mutate(sec=str_extract(filenames, "[0-9]+"), 
               name = gsub("lecture",  "", filenames), 
               link = sprintf("[%s](%s)",name, filenames))

out.read <- read %>% mutate(sec=str_extract(filenames, "[0-9]+"), 
               name = gsub("reading",  "", filenames), 
               link = sprintf("[%s](%s)",name, filenames))

out.hw <- read %>% mutate(sec=str_extract(filenames, "[0-9]+"), 
               name = gsub("hw",  "", filenames), 
               link = sprintf("[%s](%s)",name, filenames))
```

## Lecture Notes
```{r, message=FALSE, warning=FALSE, echo=FALSE}
x = out.lec %>% select(link) %>% kable(format="html") %>%
    kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), 
                  full_width=FALSE,  position = "left")
gsub("<thead>.*</thead>", "", x)
```

## Reading Materials
```{r, message=FALSE, warning=FALSE, echo=FALSE}
x = out.read %>% select(link) %>% kable(format="html") %>%
    kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), 
                  full_width=FALSE,  position = "left")
gsub("<thead>.*</thead>", "", x)
```

## Videos


## Homework Assignment Files
```{r, message=FALSE, warning=FALSE, echo=FALSE}
x = out.hw %>% select(link) %>% kable(format="html") %>%
    kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), 
                  full_width=FALSE,  position = "left")
gsub("<thead>.*</thead>", "", x)
```