---
title: "Syllabus MATH 615 - Fall 22"
output:
  html_document: 
    toc: yes
    toc_depth: 2
    toc_float: yes
    theme: readable
---


_Last updated: `r format(Sys.time(), "%a %b %d %Y %X")`_

# Course Information (check if current)

_Introduction to common procedures used to analyze data. Single and two-sample inference, analysis of variance, multiple regression, analysis of co-variance, experimental design, repeated measures, nonparametric procedures, and categorical data analysis. Examples will be drawn from Biology and related disciplines. Statistical computer packages will be introduced. Appropriate for biology, agriculture, nutrition, psychology, social science, and other majors. 3 hours discussion._


# Logistics
**Instructor:** Dr. Robin Donatello  
**Office Location:** Holt 202  
**Phone Number:** 898-5767  
**E-mail:** rdonatello@csuchico.edu  
**Prerequisites:** Basic computer literacy. Recent statistics course such as Math 105, MATH 315, or MATH 350.  
**Meeting Days and Times** MW 4-5:30, Holt XXX
**Office Hours** Holt 202: TBD See course website after week 1.  
**Class Website** https://norcalbiostat.github.io/MATH615/  
**Discord Server** https://discord.gg/tzcB4MJadW
**Google Drive**  You will be added to the Math 615 Google drive using your campus email. 

## Instructor
* **Name & pronouns** Dr. Robin Donatello  (Dr. D, she/her)
* **Office Location:** Holt 202
* **E-mail:** rdonatello@csuchico.edu
* **Best Contact Method:** Discord: https://discord.gg/tzcB4MJadW 

## Logistics
* **Prerequisites:** Math 121
* **Meeting Pattern:** Section 01: 2-3:15pm, Section 02: 3:30-4:50 pm; MLIB 045
    - Don't know how to find the library basement? There's a video in Blackboard. 

## Mode of Instruction: In Person
The mode of instruction for this course is classified as a "In Person"; this means all students are expected to attend class in person each session. At this time there is no specific plan for habitual synchronous hybrid zoom session. 

----

# What are we going to learn? (Course Learning Outcomes) {#co}

By the end of the course, students will be able to...

* Import data into a statistical analysis software program in a format that is ready to analyze. 
* Process, screen, recode, transform, and clean data.
* Describe distributions and patterns of data using visualizations and words. 
* Select and carry out an appropriate statistical analysis.
* Explain study results and limitations to a non-technical audience. 
* Understand and implement a reproducible research pipeline. 
* Become a data nerd (Optional, but recommended).


----
  
# Who are we learning it with? 

My name is Robin Donatello and my pronouns are she/her. You can address me as "Robin", "Dr. D", or some other respectful title such as "professor". 

I have a Doctorate in Public Health (DrPH) Biostatistics from UCLA, but I'm a Chico alum. I double majored in Statistics &  Biology, with minor in Chemistry, and a first generation college student who started at Butte College. 

My campus life consists of training the next generation of Scientists how to harness the power of Statistics and Data in a responsible and ethical manner, supporting students in their academic adventures through intensive advising and research, leading the Data Science Initiative (DSI) to develop Data Science capacity on our campus, and providing analytical support and statistical consulting for many projects on and off campus.

When I’m not on campus, typically I’m growing 🥕🌾🍅🍆🍏 for my family, out adventuring with my 🐶🧔🐩, or getting some 🎮🎲📚 time in.

You can learn more about the work that I do on my [website](http://www.norcalbiostat.com/)


# How are we gonna learn it? (Required materials)
Homework 0 gets you connected with these materials. 

* **Textbook**: _Practical Multivariate Analysis, 6th ed_ by Afifi, May, Donatello, Clark. [[Link]](https://www.routledge.com/Practical-Multivariate-Analysis/Afifi-May-Donatello-Clark/p/book/9781032088471)
    - This wil be used in Math 456, and is an excellent reference guide.
    - If you're curious, I get about 1% of the sale in royalty. The income is *not* why I collaborated on this edition. I used the 4th edition in grad school and really like teaching out of it. 
    - _Optional_: Open Intro Statistics 3rd edition. If you need a refresher on your basic statistics. Free PDF available at https://www.openintro.org/stat/textbook.php?stat_book=os
* **Reliable Laptop**: Expect to bring often. Contact me if this poses a problem or concern for you. 
* **Reliable internet** connection while on and off campus. ITSS can help you get this setup. 
* **Computer Software:** Data Analysis is done using statistical analysis software. Common statistical programs include SAS, STATA, R and SPSS. I am fluent in SAS, STATA and R, but can provide limited support for SPSS and Python. The choice of software you use for this class is up to you, but you will be expected to learn how to navigate the programs outside of class time. 
* **Accounts:** Google Drive (campus account), Discord, for discussion. Hack MD for collaborative notes. 


----

# How is learning measured? (What are you graded on?)

* Your final grade will be a straight sum of points earned and will be displayed as a running total in Blackboard Learn. 
* The approximate contributions per category are:  
  - Participation 15%: Slack usage, Peer reviews  
  - Written Assignments 20%: Submitted in Google Drive, but graded using a visable rubric in Blackboard Learn.  
  - Weekly Quizzes 25%: Google Forms. This replaces a midterm exam.  
  - Final exam 20%: Take home 
  - Project related assignments 20%  
* I use a standard grade cutoff of 100-90\%: A, 89-80\%: B, 79-70\%: C, 69-60\%. Plusses and minuses will be as displayed on Blackboard Learn. 

# Schedule of Topics

The general ordering of topics is:

* Data Collection and recording
* Preparing data for analysis
* Data Visualization
* Foundations for Inference:  probability distributions, point and interval estimation, Hypothesis Testing
* Inference comparing multiple samples (t-tests, ANOVA, $\chi^{2}$ tests)
* Study design, confounding, causation **(experimental design??? and pseudoreplication?)**
* Linear regression analysis (Simple and Multiple, Categorical predictors, variable selection)
* Logistic regression analysis
* Model building techniques and comparing model fit
* Special analysis topics - how to identify when linear regression models won't work. 

----

# How do you get help?

* Check out the resources on the [help](help.html) page
* Post in our Discord text chat channel. You can direct message me as well. 
* Attend student office hours: Days/times & location TBD. Will be figured out by Friday of week 1.
* Attend Community Coding: Lots of open student help hours open to any student. Hours, location and zoom link at https://www.csuchico.edu/datascience/community-coding.shtml 


----

# Class Policies and statements

## Everyone is welcome here

It is my intent that students from all diverse backgrounds and perspectives be well-served by this course, that students' learning needs be addressed both in and out of class, and that the diversity that the students bring to this class be viewed as a resource, strength and benefit. It is my intent to present materials and activities that are respectful of diversity: gender identity, sexuality, disability, age, socioeconomic status, ethnicity, race, nationality, religion, and culture. Your suggestions are encouraged and appreciated. Please let me know ways to improve the effectiveness of the course for you personally, or for other students or student groups.

I would like to create a learning environment that supports a diversity of thoughts, perspectives and experiences, and honors your identities (including race, gender, class, sexuality, religion, ability, etc.) To help accomplish this:

-  Let me know if you have a name and/or set of pronouns that differ from those that appear in your official Chico records. I make it a point to call on people by name, so please make sure that I know what you want to be called. 
        - I also want to try to pronounce your name as accurately as possible. The more you help and correct me the better I can do to honor your name. 
-   If you feel like your performance in the class is being impacted by your experiences outside of class, please don't hesitate to come and talk with me. I want to be a resource for you. Remember that you can also submit anonymous feedback using the feedback button on the schedule and help pages of the website (which will lead to me making a general announcement to the class, if necessary to address your concerns).
-   If you prefer to speak with someone outside of the course, the Office of Diversity and Inclusion is here to assist. Their number is 530-898-4764, and email [diversityoffice\@csuchico.edu](mailto:diversityoffice@csuchico.edu){.email}
-   I (like many people) am still in the process of learning about diverse perspectives and identities. If something was said in class (by anyone) that made you feel uncomfortable, please talk to me about it. (Again, anonymous feedback is always an option).

*Adapted from [Monica Linden at Brown University](https://www.brown.edu/sheridan/teaching-learning-resources/inclusive-teaching/statements)*.

Furthermore, I would like to acknowledge that Chico State stands on lands that were originally occupied by the first people of this area, the Mechoopda. I recognize their distinctive spiritual relationship with this land and the waters that run through campus. I am humbled that our campus resides upon sacred lands that once sustained the Mechoopda people for centuries.


## Attendance

Class attendance is expected. Talk to me ahead of time if you need to miss a class for a planned reason. In the event of an unplanned reason, PM me in Discord when you can so that I know you are still alive. 

* If you are not feeling well or are experiencing Covid symptoms **DO NOT COME TO CLASS**. DM me in Discord and attend online until you can return. 
* I will be taking daily attendance - this is more for my learning of names and to keep an eye out for students who may be struggling in class and deciding not to show up. 


----

## Collaboration

Collaboration on assignments is encouraged. People learn better when they have someone else to talk through concepts with. Collaboration on individual quizzes is not allowed.

According to [this document about ollaboration](https://www.csuchico.edu/scrr/_assets/documents/collaboration.pdf) linked on the CSU, Chico website: 

> Collaboration is working with another or receiving assistance from someone (e.g., a classmate, friend, or parent, whether in person or by electronic media) to complete coursework for a grade. 
> "Unauthorized collaboration" means working with others without the specific permission of the instructor on assignments that will be submitted for a grade. (i.e. in class or take home tests, quizzes, labs and homework)


Below are two quotes from [this article](https://revoteaching.blogspot.com/2021/04/ungrading-and-academic-integrity.html) that resonated with me. We will specifically talk about the idea of why students cheat in the first few weeks as a class. 

> "In my opinion students cheat for one of three reasons (or some combination): students don’t see the value in doing the work, or they don’t believe they can achieve that value if they do the work required of them, or they don’t know how to complete the work. Students cheat because they see the work as busy work, work that has no value. My students aren’t lazy. They have jobs in addition to school, they have family obligations, they have financial concerns that sometimes include housing and food insecurity. They also binge watch entertainment and play video games for hours on end. They have the ability to pay attention when their circumstances and their interests allow it."
> 
> "The solution to cheating is to address the motivation to cheat, not the consequences of cheating. Why would students cheat if they believed in the value (benefit) of the work, believed the work would produce the benefit, and believed they could complete the work? Our job as faculty is convince students of the first two ideas and help them with the third. And then we trust students to act in their own self-interest."

----

# Campus Resources

This [campus website](https://www.csuchico.edu/coronavirus/students.shtml) contains a lot of information and resources specific to our COVID-19 situation. Specifically this page contains links to resources to help you keep [learning](https://www.csuchico.edu/keep-learning/index.shtml), and [engaging](https://www.csuchico.edu/keep-engaging/index.shtml), and lots of links to student support services such as emergency grants, basic need such as healthy food and housing, tutoring, health center, financial aid and a lot more.

You can also check out the resources on the [Help](help.html) page. 

## Technology Support

-   [IT Support Services](https://www.csuchico.edu/itss/) will provide comprehensive technology support, including laptop loans and virtual technology assistance.
-   The [Office of Accessible Technology Services](https://www.csuchico.edu/oats/) will offer all students online access to a staff member during normal business hours Monday--Friday via email at [oats\@csuchico.edu](mailto:oats@csuchico.edu). Students with questions on inclusive technology or who need assistance setting up technology accommodations are encouraged to reach out.
-   If you do not have off-campus access to the Internet, [resources are available](https://www.csuchico.edu/coronavirus/internet.shtml).
-   The [Data Science Initiative](https://www.csuchico.edu/datascience/) offers year-round training workshops and seminars on data-science related topics including R.
-   [Community Coding](https://www.csuchico.edu/datascience/community-coding.shtml) (CC): Students, staff, faculty, and the public are invited to join the Community Coding sessions. Bring your computer, coding projects, and your questions to this open working environment. Think of CC as additional office hours where you have access to more teachers than just me.

## Americans with Disabilities Act

If you need course adaptations or accommodations because of a disability or chronic illness, or if you need to make special arrangements in case the building must be evacuated, please make an appointment with me as soon as possible, or see me during office hours. Please also contact Accessibility Resource Center (ARC) as they are the designated department responsible for approving and coordinating reasonable accommodations and services for students with disabilities. ARC will help you understand your rights and responsibilities under the Americans with Disabilities Act and provide you further assistance with requesting and arranging accommodations. We try our best to ensure equal access to materials in accessible formats. Reach out to your me if there is some aspect of the course materials that are inaccessible to you.

Accessibility Resource Center 530-898-5959 Student Services Center 170 [arcdept\@csuchico.edu](mailto:arcdept@csuchico.edu){.email} [http://www.csuchico.edu/arc](https://www.csuchico.edu/arc/)

----

# University Policies

## COVID-19 

The CSU requires students to be fully vaccinated and boosted against COVID-19 by February 28th, 2022, unless you have an approved exemption.  Additionally, Chico State is requiring everyone on campus to wear an approved face covering in all indoor campus spaces. Accordingly, all students are required to wear an appropriate face mask covering the nose and mouth in order to participate in this course. Policies and requirements regarding COVID-19 are subject to change pursuant to campus, local, state and/or federal guidelines.

Please note that dishonesty relating to the vaccination policy and/or your failure to comply with any other COVID-19 related safety policy or mandate, including the face covering requirement, may result in disciplinary action against you through the office of Student Conduct, Rights and Responsibilities, which can include suspension or expulsion from the California State University system. 

Individuals unable to wear a face covering due to a medical condition should contact the Accessibility Resource Center by phone at (530) 898-5959 or by email at arcdept@csuchico.edu. 


## Adding and Dropping the course

You are responsible for understanding the policies and procedures about add/drops, academic renewal, etc., found in the [CSU Chico University Catalog](http://www.csuchico.edu/catalog/). You should be aware of the new deadlines and penalties for adding and dropping classes.

The last day to add or drop classes without special permission by the instructor is 2/4/22. No adds or drops are allowed after 2/18/22 without a serious and compelling reason approved by the instructor, department chair, and college dean.


## Confidentiality and Mandatory Reoprting

As an instructor, one of my responsibilities is to help create a safe learning environment on our campus. I also have a mandatory reporting responsibility related to my role as a your instructor. I am required to share information regarding sexual misconduct with the University. Students may speak to someone confidentially by contacting the Counseling and Wellness Center (898-6345) or Safe Place (898-3030). Information on campus reporting obligations and other Title IX related resources are available here: www.csuchico.edu/title-ix.


## Academic Integrity

Academic integrity is defined as “a commitment, even in the face of adversity, to five fundamental values: honesty, trust, fairness, respect, and responsibility”. From these values flow principles of behavior that enable academic communities to translate ideals to action. Academic integrity is expected and required. No forms of cheating or plagiarism will be tolerated. Please see your student handbook at https://www.csuchico.edu/scrr/integrity.shtml if you have questions about the meaning of these terms or the consequences of violating academic integrity.

