---
title: "Syllabus Math 615 Fall 19"
output:
  html_document: default
  pdf_document: default
---

# Course Description

_Introduction to common procedures used to analyze data. Single and two-sample inference, analysis of variance, multiple regression, analysis of co-variance, experimental design, repeated measures, nonparametric procedures, and categorical data analysis. Examples will be drawn from Biology and related disciplines. Statistical computer packages will be introduced. Appropriate for biology, agriculture, nutrition, psychology, social science, and other majors. 3 hours discussion._


# Logistics
**Instructor:** Dr. Robin Donatello  
**Office Location:** Holt 202  
**Phone Number:** 898-5767  
**E-mail:** rdonatello@csuchico.edu  
**Prerequisites:** Basic computer literacy. Recent statistics course such as Math 105, MATH 315, or MATH 350.  
**Meeting Days and Times** TR 11-12:15, Holt 155  
**Office Hours** Holt 202: TBD  
**Class Website** https://norcalbiostat.github.io/MATH615/  
**Slack Channel**  http://math615.slack.com  You will be sent an email invitation to your campus email.   
**Google Drive**  You will be added to the Math 615 Google drive using your campus email. 

You can download the Syllabus in PDF form by clicking [[this link]](syllabus_615_f19.pdf).


# Learning Outcomes

By the end of the semester students will be able to 

* Import data into a statistical analysis software program in a format that is ready to analyze. 
* Process, screen, recode, transform, and clean data.
* Describe distributions and patterns of data using visualizations and words. 
* Select and carry out an appropriate statistical analysis.
* Explain study results and limitations to a non-technical audience. 
* Understand and implement a reproducible research pipeline. 
* Become a data nerd (Optional, but recommended).


# Required Materials

* **Textbook**: _Practical Multivariate Analysis, 5th ed_ by Afifi, May Clark. Available cheaper at [Amazon](https://www.amazon.com/Practical-Multivariate-Analysis-Chapman-Statistical/dp/1439816808) 
    - The 6th edition is coming out near December, so rent the 5th edition if you can. 
    - This wil be used in Math 456, and is an excellent reference guide.
    - _Optional_: Open Intro Statistics 3rd edition. If you need a refresher on your basic statistics. Free PDF available at https://www.openintro.org/stat/textbook.php?stat_book=os
* **Reliable Laptop**: Expect to bring often. Contact me if this poses a problem or concern for you. 
* **Reliable internet** connection while on and off campus. ITSS can help you get this setup. 
* **Computer Software:** Data Analysis is done using statistical analysis software. Common statistical programs include SAS, STATA, R and SPSS. I am fluent in SAS, STATA and R, but can provide limited support for SPSS. The choice of software you use for this class is up to you, but you will be expected to learn how to navigate the programs outside of class time. 
* **Accounts:** Slack, for discussion. Hack MD for collaborative notes. 


# Grading

* Your final grade will be a straight sum of points earned and will be displayed as a running total in Blackboard Learn. 
* The approximate contributions per category are:  
  - Participation 15%: Slack usage, Peer reviews  
  - Written Assignments 20%: Submitted in Google Drive, but graded using a visable rubric in Blackboard Learn.  
  - Weekly Quizzes 25%: Google Forms. This replaces a midterm exam.  
  - Final exam 20%: Take home 
  - Project related assignments 20%  
* I use a standard grade cutoff of 100-90\%: A, 89-80\%: B, 79-70\%: C, 69-60\%. Plusses and minuses will be as displayed on Blackboard Learn. 

# Schedule of Topics

The general ordering of topics is:

* Data Collection and recording
* Preparing data for analysis
* Data Visualization
* Foundations for Inference:  probability distributions, point and interval estimation, Hypothesis Testing
* Inference comparing multiple samples (t-tests, ANOVA, $\chi^{2}$ tests)
* Study design, confounding, causation
* Linear regression analysis (Simple and Multiple, Categorical predictors, variable selection)
* Logistic regression analysis
* Model building techniques and comparing model fit
* Special analysis topics - how to identify when linear regression models won't work. 

----

# Policies

## Adding and Dropping the course

The last day to add or drop classes without special permission by the instructor is 9/6/19. No adds or drops are allowed after 9/20/19 without a serious and compelling reason approved by the instructor, department chair, and college dean.


## Americans with Disabilities Act

If you need course adaptations or accommodations because of a disability or chronic illness,  or if you need to make special arrangements in case the building must be evacuated, please make an appointment with me as soon as possible, or see me during office hours. Please also contact Accessibility Resource Center (ARC) as they are the designated department responsible for approving and coordinating reasonable accommodations and services for students with disabilities. ARC will help you understand your rights and responsibilities under the Americans with Disabilities Act and provide you further assistance with requesting and arranging accommodations.

Accessibility Resource Center  
530-898-5959   
Student Services Center 170  
arcdept@csuchico.edu  


## Chico State Basic Needs Project

The **Hungry Wildcat Food Pantry** provides supplemental food, fresh produce, CalFresh application assistance and basic needs referral services for students experiencing food and housing insecurity.

All students are welcomed to visit the Pantry located in the Student Service Center 196, open Monday-Friday, 11am-4pm or call 530-898-4098. 

Please visit the Chico State Basic Needs website http://www.csuchico.edu/basic-needs for more information.

 
-----

_Last updated: `r format(Sys.time(), "%a %b %d %Y %X")`_
 
