---
title: 'Week 1 8/21 - 8/27'
date: "Last Updated `r Sys.time()`"
output:
  html_document:
    highlight: tango
    theme: flatly
    toc: yes
    toc_float: yes
css: css/customh5.css
---

```{r,echo=FALSE, warning=FALSE, message=FALSE}
library(knitr)
#library(rmarkdown)
opts_chunk$set(warning=FALSE, message=FALSE) 
```


# Tuesday: Introduction to the class
Goals: 

* Understand how to navigate the course website resources
* Create learning support groups
* Understand what statistical programming software options are available to you, and what support systems they come with. 
* Understand the concept of reproducible research and why it's important. Understand at what level reproducibility is expected in this class. 

## Prepare before class
* Read the [Syllabus](docs/syllabus_615_f17.html)
* Bookmark this class website 
* Purchase the [textbook](https://www.amazon.com/Practical-Multivariate-Analysis-Chapman-Statistical/dp/1439816808) (PMA5). Pricey, but honestly one of those books that you are likely to keep as a reference textbook. 
* Read [Passion Driven Statistics](docs/PDS_Intro_Stat.pdf) (ignore last page about timeline). We are going to take a similar approach in this class to conducting an analysis. 
* Review [these slides](http://benmarwick.github.io/UW-eScience-reproducibility-social-sciences/#/) on reproducible research in the social sciences.


## In class
* [Introduction to the class](docs/lec01_intro_class.html) notes
* Discuss logistics and software options

##### Assignments
* Create a MATH615 folder on your computer - all course related files go in here. 
* Blog post: Introduction/bio of yourself. 
    - What's your research area?
    - One non-academic interest or hobby
* Decide on the software program you will use. (Due before next Tuesday)
    - Nutrition majors are highly recommended to choose SPSS since you will be using that in NSFC 600. 
    - Review the support options above before making your decision.  
    - You are welcome to switch at any time, but acknowledge it will be hard (but not impossible) to get caught up.
    - Get your laptop ready to analyze data by next Tuesday. 
* Blog post (2): Reproducible research plan.
    - Write up a plan for how you will conduct reproducible research in this class.
    - Be explicit and detailed, consider these instructions for a "you" in 6 months. (yes these plans can, and will change)
* Read PMA5 Ch 2. Here is a [scanned PDF](docs/PMA5 Ch 2 and 3.pdf) if you don't have the book yet.
    
----

# Thursday: Orientating yourself to data
Goals: 

* Identify different data types according to Stevens's Classifications. 
* Understand how to use a data dictionary (codebook)
* Learn about the Add Health data that you will be analyzing this semester. 

## Prepare
* Read the Personal Codebook Assignment [[instructions]](hw/RQ_personal_codebook_assignment.html)
* Download the following data sets and codebooks from my [data](https://norcalbiostat.netlify.com/data/raw_data/) page into a `MATH615/data` subfolder on your computer. 
    - medical-records.pdf
    - Add Health.csv
    - ParHIV.xlsx
    - depress.txt
    
We'll use the Add Health codebook today, but the others next week. So might as well grab all while you're there. 

## In class
* Medical Record data entry and codebook creation [[Instructions]](docs/MedRecords.html)
* Personal Codebook Assignment

##### Assignments
* Review the AddHealth codebook front matter and choose 3-5 areas of interest. 
    - Write a blog post about what you are thinking of researching. 
    - Review a few of your other classmates posts to get a sense of what others are looking into. Feel free to comment! Giving feedback is an important part of this class.  
* Personal Codebook and Research Question [[Assignment]](hw/RQ_personal_codebook_assignment.html) 
    - There are a lot of common interests (in terms of general nutrition) in this class, so keep an eye on your classmates blogs to make sure you don't end up doing the exact same thing. 
    - There can be some overlap, but avoid the **exact** same RQ. 
* Read PMA5 Ch3 (Preparing Data for Analysis)
* Read next week's overview so you know how to prepare for Tuesday. 




