---
title: 'Week 2: 8/28 - 9/1'
date: "Last Updated `r Sys.time()`"
output:
  html_document:
    highlight: tango
    theme: flatly
    toc: yes
    toc_float: yes
css: css/customh5.css
---

```{r,echo=FALSE, warning=FALSE, message=FALSE}
library(knitr)
#library(rmarkdown)
opts_chunk$set(warning=FALSE, message=FALSE) 
```

# Tuesday: Data Import & Preparation
Goals: 

* Be able to import different data types into your software program of choice (SPC)
* Learn how to identify mistakes and missing data in data using tables and summaries
* Learn how to correct certain mistakes
* Learn how to recode variables into new ones


## Prepare
* Review the [data prep notes](docs/lec02_data_prep.html) 
    - Starting to replicate the code concepts in these notes in your SPC. 

## In Class
* Walking through the data management process on the depression data set. 

## Resources
* R (Data Import)
    - https://norcalbiostat.github.io/MATH130/materials/day3-import-and-factors.html 
    - http://dwoll.de/rexrepos/posts/dfImportExport.html 
    - https://www.datacamp.com/community/blog/an-introduction-to-cleaning-data-in-r#gs.7=03Hnc 
* R (Data Preparation)
    - http://dwoll.de/rexrepos/rerR_Basics.html 
    - https://stats.idre.ucla.edu/r/modules/ 
    - https://www.datacamp.com/community/blog/an-introduction-to-cleaning-data-in-r#gs.7=03Hnc 
* SPSS (Data Import)
    - https://www.ibm.com/support/knowledgecenter/en/SSLVMB_22.0.0/com.ibm.spss.statistics.help/spss/base/datafile_auto_0.htm
    - http://libguides.library.kent.edu/SPSS/ImportData
* SPSS (Data Preparation)
    - https://www.ibm.com/support/knowledgecenter/en/SSLVMB_22.0.0/com.ibm.spss.statistics.help/spss/base/data_prep.htm 
    - https://stats.idre.ucla.edu/spss/modules/


##### Assignments
* Explore some variables within your chosen sections of Add Health 
    - Blog about what variables you chose and why
    - Discuss any recoding you think you may want to do, or data problems that will have to be fixed. (_Think about the data management questions in the notes_) 
* Start a data management file for the Add Health data. You wil submit this to BBLearn by the due date. 
    - This must be a single script file that imports the data, does cleaning, and saves the cleaned data set with a new name. 
    - It does not have to be comprehensive or finished! I just want to make sure you are getting started in a reproducible manner. 
    
----

# Thursday: Literature Review & Citation Assignment

## Prepare
* Read: [How to read a Journal Article](docs/How to Read a Journal Article.pdf)

## In class
* Brief discussion of literature review & citation formats
* Citation Assignment _or_ continue data management. 


##### Assignments

* Citation assignment [[Instructions]](hw/Citation_Assignment.html)
    - [Example submission](docs/Citation Assignment Example.pdf)



