---
title: 'Week 3 9/4 - 9/10'
date: "Last Updated `r Sys.time()`"
output:
  html_document:
    highlight: tango
    theme: flatly
    toc: yes
    toc_float: yes
css: css/customh5.css
---

```{r,echo=FALSE, warning=FALSE, message=FALSE}
library(knitr)
#library(rmarkdown)
opts_chunk$set(warning=FALSE, message=FALSE) 
```


# Tuesday: Univariate Data Viz
Goals: 

* Learn how to create univariate data graphics
* Describe the distribution of a single variable in sentence form using summary statistics and pointing out specific features of the graphics as evidence to support your interpretation. 

## Prepare 
* Review both the following items. We are only exploring a single variable at first.
    - [PMA6 Data Viz ch DRAFT](docs/pma6_ch4_draft.pdf)
    - [Data Viz tutorial](https://norcalbiostat.github.io/MATH130/materials/day56-data-viz.html). 
* Prepare your computer to use either the `parhiv` and/or `depress` data sets, or the `dsmall` subsample of the `diamonds` data set (also available for download on my [cleaned data](https://norcalbiostat.netlify.com/data/cleaned_data/) page)
          

## In class
* Reproduce all univariate graphics and tables in your SPC. 
    - The examples in PMA6 use the `parhiv` and `depress` data sets. 
    - The examples in Data viz tutorial use the `diamonds` data set that comes with `ggplot2` package. 
* Discuss interpretations for all univariate graphics. 


## Resources
* SPSS
    - [IBM knowledge center on Working with multiple data sources](https://www.ibm.com/support/knowledgecenter/en/SSLVMB_22.0.0/com.ibm.spss.statistics.help/spss/base/multiple_datasets_intro.htm)
    - [UCLA IDRE graphics module](https://stats.idre.ucla.edu/spss/seminars/spssgraphics/graphics-in-spss/)
    - [IBM knowledge center on graphics](https://www.ibm.com/support/knowledgecenter/en/SSLVMB_22.0.0/com.ibm.spss.statistics.help/spss/base/idh_idc_cg_help_main.htm)
    - [IBM knowledge center on saving output as Word](https://www.ibm.com/support/knowledgecenter/en/SSLVMB_24.0.0/spss/tutorials/outputtut_msapps.html)
* R
    - [UCLA IDRE graphics module](https://stats.idre.ucla.edu/r/modules/exploring-data-with-graphics/)
    - [Data Camp ggplot lesson](https://www.datacamp.com/courses/data-visualization-with-ggplot2-1)
    - [ggplot2 documentation from the developer](http://ggplot2.tidyverse.org/index.html)


# Thursday: Data screening
Goals: 

* Learn how to use graphics to screen the data for normality. 
* Learn how to transform the data to achieve an approximate normal distribution

## Prepare
* Read PMA5 Chapter 4: Data Screenings and Transformations


## In class
* [Data Screening](docs/lec03_data_screen.html) notes


##### Assignments
* Univariate graphing assignment. [[Instructions]](hw/Univ_Graphing.html)

          



