---
title: 'Week 5: 9/18-9/24'
date: "Last Updated `r Sys.time()`"
output:
  html_document:
    highlight: tango
    theme: flatly
    toc: yes
    toc_float: yes
css: css/customh5.css
---

```{r,echo=FALSE, warning=FALSE, message=FALSE}
library(knitr)
#library(rmarkdown)
opts_chunk$set(warning=FALSE, message=FALSE) 
```


# Tuesday: Bivariate Comparisons
Goals: 

* Identify patterns or trends in bivariate relationship graphics.
* Create summary statistics for continuous variables for each level of a categorical variable.


## Prepare 
* Review both items - specifically for the bivariate relationships. (No multivariate yet!)
    - [PMA6 Data Viz ch DRAFT](docs/pma6_ch4_draft.pdf)
    - [Data Viz tutorial](https://norcalbiostat.github.io/MATH130/materials/day56-data-viz.html). 

## In class
* Keeping your cross-tabs straight
    _ Row vs column percents
    - A within B, or B within A? 
* Introduce the [Bivariate Graphing assignment](hw/biv_graphing.html)


##### Assignments
* [Bivariate Graphing assignment](hw/biv_graphing.html)
    - Similar to the univariate, post this assignment as a blog post and then conduct a peer review. 

# Thursday: Open work time
_Robin out of town, Edward Roualdes will cover_

Goals: 

* Finish any open assignments. 
