---
title: 'Week 6: 9/25-10/1'
date: "Last Updated `r Sys.time()`"
output:
  html_document:
    highlight: tango
    theme: flatly
    toc: yes
    toc_float: yes
css: css/customh5.css
---

```{r,echo=FALSE, warning=FALSE, message=FALSE}
library(knitr)
#library(rmarkdown)
opts_chunk$set(warning=FALSE, message=FALSE) 
```


# Tuesday: Choosing Appropriate Analysis
Goals: 

* Identify dependent and independent variables
* Identify appropriate choices for analysis for each combiation of data types
* Start your presentation slides file in Google Drive. 

## Prepare 
* Read PMA5 Chapter 5
* Review new items on project page. 

## In class

### Selecting appropriate analysis

**Considerations:**

* Purpose of analysis.  
* Types of variables in data set.  
* Data used in analysis.   
* Assumptions needed; satisfied?  
* Choice of analyses is often arbitrary: consider several  

**Example:** 

5 independent variables: 3 interval, 1 ordinal, 1 nominal  

1 dependent variable: interval

Analysis options  

- Multiple regression: pretend independent ordinal variable is an
  interval variable use dummy (0 /1) variables for nominal variables
- Analysis of variance: categorize all independent variables
- Analysis of covariance: leave variables as is, check assumptions
- Logistic regression: Categorize dependent variable: high, low
- Survival analysis: IF dependent variable is time to an event

Unsure? Do several and compare results. 


### Poster Peparation
- Introduce new additions to project page. 

----

# Thursday: Exam 1

This exam emphasizes correct identification of data, interpretation of univariate and bivariate graphics and use of summary statistics. [[Sample Exam]](https://norcalbiostat.github.io/MATH315/docs/Sample_Exam_1.pdf)

##### Assigments
* Error Assessment (Optional)
    - Take your returned exam and go over it carefully. 
    - Print out [this form](docs/error_assessment.pdf) and use it to understand what types of mistakes you are making. 
    - Correct your exam on a new piece of paper. 
    - Go over your returned exam with a tutor, with a specific eye towards what _type_ of mistakes you made. **Do not go to a tutor until you have made your own corrections**
    - Have the tutor sign off on your visit. 

You can earn up to half credit of the total missed points back by returning the form, corrected work and exam back to me by 10/20. 

* Exam Materials: [NC Births Codebook](docs/Codebook_for_NCBirths.pdf), [R code](docs/Exam1_F17_R_Code.pdf)

