---
title: 'Week 8: 10/9 - 10/15'
date: "Last Updated `r Sys.time()`"
output:
  html_document:
    highlight: tango
    theme: flatly
    toc: yes
    toc_float: yes
css: css/customh5.css
---

```{r,echo=FALSE, warning=FALSE, message=FALSE}
library(knitr)
#library(rmarkdown)
opts_chunk$set(warning=FALSE, message=FALSE) 
```


# Tuesday: Bivariate Inference 

Goals: 

* Review how we use the normal distribution to compare two means, and two proportions. 
* Conduct these analyses in your software program of choice. Understand how to read the output. 

## Prepare 

* Read Section 5.3 (difference of two means) and 6.2 (difference of two proportions) in the Open Intro textbook. There are several videos that accompany these section. 
    - The PMA5 book covers primarily multivariable analyses techniques. Not bivariate.  

## In class

* Review two sample t-tests in preparation for multiple group comparisons. 
* Using the variables chosen in your foundations worksheet - conduct a test of means and proportions in your software program of choice. Learn how to read the output. 

## Resources

* [CHOOSING THE CORRECT STATISTICAL TEST IN SAS, STATA, SPSS AND R] https://stats.idre.ucla.edu/other/mult-pkg/whatstat/

----

# Thursday: ANOVA
Goals: 

* Describe why ANOVA is better than multiple comparisons
* Conduct an ANOVA in your software program of choice and interpret the results. 


## Prepare
* Read Section 5.5 (comparing many means) in Open Intro textbook. Watch the associated videos. 
* Introduce yourself to the [Bivariate Inference](hw/Bivariate_Inference.html) Assignment. 
    - Here is a [[PDF]](hw/Bivariate_Inference.pdf) version if you would like to print/annotate. 
* Passion Driven Statistics [[Chapter 11]](http://passiondrivenstatistics.com/2016/05/11/r-chapter-11/) Video. 
    - This video uses R for the analysis, but the ANOVA table output in SPSS (and any other stat program) will look similar. The information all the way through is important.


## Resources
UCLA IDRE pages: One Way ANOVA in [[SPSS]](https://stats.idre.ucla.edu/spss/whatstat/what-statistical-analysis-should-i-usestatistical-analyses-using-spss/#1anova) or [[R]](https://stats.idre.ucla.edu/r/whatstat/what-statistical-analysis-should-i-usestatistical-analyses-using-r/#1anova)

## In class

* Introduction to the bivariate inference assignment. 
* Discuss how analyzing the ratio of variances can tell you about the group means. 
* Conduct and interpret an ANOVA using your software program of choice. 



##### Assignments
* [Bivariate Inference](hw/Bivariate_Inference.html) Assignment.
    - R code [template](hw/bivariate_Inference_template.Rmd) -- to be used by the R users.
    - You are encouraged to upload your working Bivariate Assignment document as you finish an analysis, and review other's work to see how they approached that problem. This will occur several times before the submission is due for grading. 

