---
title: 'Week 12: 11/4 - 11/12'
date: "Last Updated `r Sys.time()`"
output:
  html_document:
    highlight: tango
    theme: flatly
    toc: yes
    toc_float: yes
css: css/customh5.css
---

```{r,echo=FALSE, warning=FALSE, message=FALSE}
library(knitr)
#library(rmarkdown)
opts_chunk$set(warning=FALSE, message=FALSE) 
```


# Tuesday: Interactions and Categorical Predictors
Goals: 

* Explain the difference between an interaction model and stratification
* Identify how you can test a moderator using an interaction term
* Write a mathematical model that contains a categorical predictor using reference coding. 
* Interpret categorical predictor


## Prepare 
* Review the second half of the MLR notes [[HTML]](docs/lec07_MLR.html) [[PDF]](docs/lec07_MLR.pdf)
* PMA5 CH7.8 (interactions)
* PMA5Stratification (PMA5 7.9)

## In class
* Primarily lecture, board work on interpreting categorical predictors
* Time pending, work on the Regression Assignment [[HTML]](hw/Regression_Assignment.html), [[PDF]](hw/Regression_Assignment.pdf)

----

# Thursday: Transformations: Log and Logit

Goals: 

* Interpret a regression where the outcome has been log transformed 
* Learn how to fit a model to a binary outcome
* Interpret logistic regression coefficients as Odds Ratios


## Prepare 
* Read [[UCLA IDRE page]] https://stats.idre.ucla.edu/other/mult-pkg/faq/general/faqhow-do-i-interpret-a-regression-model-when-some-variables-are-log-transformed/ 
* Multiple Regression Notes [[HTML]](docs/lec07_MLR.html) [[PDF]](docs/lec07_MLR.pdf)
* PMA5 CH 12
* Review the notes on Logistic Regression [[HTML]](docs/lec08_LogReg.html) [[PDF]](docs/lec08_LogReg.pdf)


## In class
* Primarily Lecture and discussion

##### Assignments

* [Regression Assignment](hw/Regression_Assignment.html)
