---
title: "Formulating research questions"
output:
  pdf_document: 
  html_document:
    highlight: tango
    theme: flatly
    toc: yes
    toc_float: yes
urlcolor: blue
css: ../css/custom_css.css
---

_Last Updated: `r format(Sys.time(), "%a %b %d %X")` _   
<br>


By the end of this topic students will understand 

* How to use a codebook to connect measured items to research question topics
* How to formulate a testable hypothesis
* How to review literture to refine their research question

---

<div class="alert-info">
#### Answer these questions in the [HackMD collab notes](https://hackmd.io/@norcalbiostat/02_rq). Then when prompted, share with your neighbor. 

1. What are the characteristics of a good research question
2. What is the one essential piece you need to review before you can formulate a research question?

</div>


# 1. Define a topic area
* Nice and broad

> Ex: Vaping in adolescents.

# 2. Choose measures
* You can't conduct research on data you don't have. 
* When using a secondary data source, this is where the codebook is used. 

> Ex: Age of respondent, how often they vape in a week, family structure (two parent household?), parental education, parental smoking status...

# 3. Draft a few Research Questions
What specific questions are you interested in trying to answer about your topics?

* One of the simplest research questions that can be asked is whether two measures are associated. 
* Must be written as a testable hypothesis **(can you answer yes or no to the question?)**
* Good RQ's are made up by asking how does 1 explanatory variable affect 1 response variable. 
    - You can always build up but you have to start with 2.
* Must connect directly with your chosen measures. 
    - Can you clearly identify what your independent and dependent variables are?
* Read your question out loud. Does it make sense? 

> Ex: Do teens who vape have parents that smoke? 

**A note about the `explanatory` vs `response` variable terminology:**

Depending on your field of study, these terms may be called different things. Statisticians tend to say _covariate_ and _outcome_. Public health and the Social Sciences tend to use Independent variable (IV) and dependent variable (DV). Regardless of the word you use... the explanatory variable tries to **explain** the response variable. 

| Explanatory          | Response           |
|----------------------|--------------------|
| X                    | Y                  |
| independent variable | dependent variable |
| covariate            | outcome            |



<div class="alert-info">

Write an example of a research question.

</div>



# 4. Conduct a literature review

Literature reviews help you identify gaps in the current literature regarding your research topic, and refine your research question. 

> What is a literature review?

* Examination of the body of work that has been written about your topic
    - In this context, it is a VERB (but it can also be a NOUN)
* Why do I need to do it?
    - To understand the state of knowledge on your topic
    - You must do this because others have researched something along the same lines as what you are interested in
    - So you will be able to learn what methodologies, theories, or models others have applied to your research question
* It will help you ask your question better
* To refine (narrow, expand, focus, modify) your own research question 
* To contribute to your area with something new, which is science!
* It is the way you always introduce your topic, which you will be writing
    - Helps you create your argument as to why this is important
* It helps you interpret what you results are (later)
    - It gives you the context to evaluate your results



## Primary source literature
* Journal articles reporting study results – a researcher did a literature review, had data, analyzed it, and wrote up results in context.
* This is what you will be doing later, in poster form. 

## Secondary source literature
* Textbooks, handbooks, review papers, theoretical articles, magazines and newspapers (you CANNOT use these as a source for your paper)
* What are some problems with secondary source literature? 
    - Can describe or interpret results incorrectly
    - Can leave out important details


## How can you tell if it a primary source? 
* It has a title, abstract, introduction, method (with participants), results, discussion, and reference list.



<div class="alert-info">

What do "participants" look like for research in your field?

</div>


## A few tips for your literature search

* Try to use articles that are published within the last 5-10 years
* Read the abstract, if sounds similar to your topic, read the participants, methods, and discussion at a glance then decide if you should keep or not
* As you read the literature, there should be an exchange between your research question and what you are learning. 
* The articles you are reading about should inform you about the association you are interested in testing.
    - Allows us to see what we KNOW and what we DO NOT KNOW
* Give special attention to the "future research" sections of the articles that you read. 
* Try to find a few articles that are looking specifically what you are looking at in terms of the association between your two specific topics.
    - This will tell you what we already know and the "future research" in the discussions and conclusions sections will tell you questions that need more research.
    - If you can look at an association that has recently been identified as "area for future research" we have hit the jackpot in terms of topics.
* How to read a journal article is available on the course website under Articles


# 5. Refine your research question

* Based on your literature review some of your draft questions may already be answered, or you noticed that your question is a still too vague. 
* Revisions are a part of research. 


# <a href="https://norcalbiostat.github.io/MATH615/"><button type="button">Back</button> </a>

