---
title: "Introduction to MATH 615"
date: "Last Updated `r Sys.time()`"
output:
  html_document:
    highlight: tango
    theme: flatly
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
css: ../css/customh5.css
---

# Navigating course resources
* My website: http://norcalbiostat.com
    - First stop for all class materials
    - Links to individual classes, but shared resources on programming and data. 
* This class website https://norcalbiostat.github.io/MATH615/ 
    - Landing page for announcements
    - Details on weekly topics can be found on the schedule
    - Includes links to notes, assignments and additional materials
* Both are mobile friendly. 
* Often links will be broken. Typo's happen. Notify me via slack and I'll get to it asap. 
* The syllabus covers course details such as grading, office location and classroom policies. 


# Online systems

* Blackboard Learn (BBL) used for recording grades
    - Some assignments will ask you to "drop a note" in BBL when your assignments are ready for grading. 
* Assignments will be turned in and peer reviewed through Google Drive. 
* The textbook is used for data, reading and learning content. Sometimes problem sets. 
    - Great long term resource, but a new edition will be coming out next year. 
    - I've provided a draft for select chapters in the 6th edition. 
* Slack will be used for outside class discussions, homework help and general chatter. 
    - I will not answer programming questions through email. 
    - Download either the phone app or the desktop app (I use both) 
    - I don't think push notifications are not automatically turned on. You must opt in. 
* Lecture notes
    - Combination of Applied Statistics notebook, and stand alone lecture notes like these. 
    - Available as PDF or HTML. 

    
# Descriptive vs. Inferential Statistics
* Two main phases of Statistics. 
    - Also called Exploratory and Confirmatory 
* [Passion Driven Statistics](../reading/PDS_Intro_Stat.pdf) 
    - Backbone theory behind the class. Read this PDF to get a sense of how statistics fits into science. 
    - The videos can be used as an additional learning tool. 
* Google `data analysis lifecycle` and look at [images](https://www.google.com/search?q=data+analytics+life+cycle&newwindow=1&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi32cepp9DcAhXLhVQKHYR8AScQ_AUICigB&biw=1482&bih=876). What sense do you get? 

# Project

* This course will revolve around a data analysis project. 
* Individual projects, but you will collaborate with each other
* All assignments are desgined to support your research
* Must choose a project out of select data sets.
    - Individual research is typically not developed or robust enough to be demonstrative. 
* More details are on the [project](project.html) page. 

# Assignment Submission
See the course [FAQ](faq.html) page. 


# Computing and Reproducibility

* No more TI-83, modern statistics is computational based. 
* Big push for open research in the Natural Sciences. 
    - Sharing code & data. Sometimes required along with manuscript for publishing. 
* Reproducibility. Give someone else access to your data and code, and they can replicate your findings. 
    - We will practice this in this class. 
    - I practice this by putting all class material online with a cc-by license. (others are free to copy and share my work with acknowledgement)
* Review these [Slides](http://benmarwick.github.io/UW-eScience-reproducibility-social-sciences/#/) on reproducible research in the social sciences.
    - I will not require any measure of version control or open source coding in this class. 
* Be mindful about file naming conventions (slide 11). Make a plan and stick with it. 
    * https://www.xkcd.com/1459/
* Expect to bring your laptop every day to class. 
    - The more reading and content learning done outside of class, the more time for in class analysis and discussion
    

# Software program of choice (SPC)   
* This class is not a class on how to use the software program. You will be learning that on your own or in another class. 
* All my lecture notes use R. This entire website is built with R. R is a pioneer in generating reproducible and publishable quality reports. 
    - [Here's an student-generated example](../reading/Final_chem_report.pdf)
* I will not dictate which software program you use in this class. 
* But I will expect you to navigate and use code. You can point and click your way to an answer, but code must be saved and reusible with minimal changes. 
* Be open to new things, there is power in being polyglottal. 
* The first few weeks will be ramp up time. 


## SPSS
* Purchase v24 or v25 from http://www-03.ibm.com/software/products/en/spss-stats-gradpack for $50 for 6mo rental. 
* Point and click, but can save code and write scripts. 
* Stand alone program. No integration. Licenses are not cheap. 
* Will be used again in NSFC 600 (no exp necc for that class either)
* On campus resources: From the desk of David Philhour (BSS) 
    - Open computer labs in Butte Hall (207, 211) with many open lab hours.
    - Tutoring center in AJH108 run by Dr. Penelope Kuhn. 
    - The psyc depth lab is Modoc 224 but is pretty impacted with classes Monday thru Thursday. Friday's are pretty open.
* Off Campus resources
    - Kent State University Tutorials: https://libguides.library.kent.edu/SPSS/home 
    - UCLA Institute for Digital Research and Education: https://stats.idre.ucla.edu/spss/ 
    - Recommended selection of YouTube videos https://www.youtube.com/results?search_query=andy+field+spss+tutorials

## R 
* Free. Installation Instructions here: https://norcalbiostat.netlify.com/post/software-overview/
* Harder up front, more powerful in the end. 
* Seamless integration with a multitude of other scientific analysis and reproducible reporting mechanisms. 
* Becoming much more popular in all scientific fields of study. One of the primary languages for Data Science. 
* Google at [diagram](https://osf.io/69gub/wiki/home/) of the `tidyverse` (a suite of functions in R). Compare it to the images of the data analysis life cycle. What sense do you get? 
* Need some motivation? 
    - https://www.psychologicalscience.org/observer/why-you-should-become-a-user-a-brief-introduction-to-r 
    - https://osf.io/j28w7/
    - https://www.youtube.com/watch?v=jn_3N_o2d6Q
* On campus resources
    - Introduction to R (MATH 130) 1 unit CR/NC
    - Data Science Initiative workshops, talks, open drop in analysis time. 
* Off Campus resources (a few)
    - Chico R Users Group 
        - [Meetup](https://www.meetup.com/Chico-R-Users-Group/)
        - [Google l-serv](https://groups.google.com/forum/#!forum/chico-rug)
    - [Data camp](http://www.datacamp.com)
    - [Quick-R](http://www.statmethods.net/)
    - [Cookbook for R](http://www.cookbook-r.com/)
    - [R Examples Repository](http://dwoll.de/rexrepos/) (This site was also built using R Markdown, is open source and a fabulous example of reproducible research!)

   
   
## SAS? STATA? Python? 
* SAS has only now working on literate and integrated programming by using Jupyter notebooks and SAS University Edition (free)
* Stata has a few user written packages that allow for the integration of LaTeX or markdown into your code document. 
* Python is the other primary language for Data Science. I am in the process of learning Python but the capabilities are very great. If you're thinking this route be sure to use Jupyter notebooks. 


----

Back to the Week 1 overview: https://norcalbiostat.github.io/MATH615/wk/wk01.html


