---
title: "Research Plan Outline"
output:
  pdf_document: default
  html_document:
    highlight: tango
    theme: flatly
css: ../css/customh5.css
---

# Overview
Your research plan is an important component of your final research project. Not only is it worth about 10% of your project grade, it will also act as the basis for your final poster. You will spend the next several weeks writing your research plan. Before you do that, however, it is important to have an outline in place. For this assignment, you will use the outline template below to begin thinking about how your research plan paper will come together.

Use the model sections found in the reading [writing about empirical research](../lecture/lec02_writing_em.html) to help guide your writing. 


# Writing Template
## Title
Using what you know now about your project and the model title in the reading, develop a working title fully knowing it is going to probably change. 

* Your title should summarize the main idea of your research question.
* Must include the variables under investigation.
* Must be fully explanatory when standing alone. 
* Include the terms "association between" or "relationship between" in your title to join your variables of interest.  
 

## Introduction 
Write an opening statement or questions to grab the reader. This statement introduces your topic and gives your rationale for the study. This is going to be a working opening statement that will develop more as you go.	
    
* Create a basic outline of topics you know you will need to discuss to be able to identify major trends in the literature and emphasize major findings. 
* As you have been reading you should have been seeing some of the same topics/findings/themes reappearing, these would be good topics to put into a basic outline.

## Method
* Name the data set and discuss at least 3 key features of the sample or way data were collected.
    - The three key features should have supporting data.
* Create one outline point for each of your variables. 
    - What are they and how were they measured?
 
## Predicted Results
* At least 2 outline points stating how you think your variables will be related/associated. 
    - Look back to your research question and think about "answering" it.
    - Use some of your findings from your bivariate graphing assignment to help here. 

# Example submissions


##### Submission
* Write your paper directly in the `Research Proposal/Incoming` folder in Google Drive with the file name: _userid_proposal.pdf_
* This assignment will be peer reviewed. 
    - You will only review one person's paper here. Do a thorough job, looking for spelling and grammer as well as for content and clarity. Provide 3-5 substantial suggestions for changes. 

