---
title: "Graphing Bivariate Relationships"
output:
  html_document:
    highlight: tango
    theme: flatly
css: ../css/customh5.css
---

# Assignment Overview

To fully explore the relationship between two variables both summary statistics and visualizations are important. For this assignment you will describe the relationship between these four specific combinations of data types: 

* Categorical (or Binary) explanatory and categorical (or binary) explanatory variable. (C ~ C)
* Quantitative explanatory and categorical (or binary) explanatory variable. (Q ~ C)
* One of the above but specifically with a binary variable (B ~ C, C ~ B, or Q ~ B)
* Quantitative response and quantitative explanatory variable. (Q ~ Q)


# Setup

I.  Determine what variables you want to graph based on your research topic. 
    * You will need a mixture of categorical and quantitative variables for this assignment. 
    * You should use variables that are relevant to your research topic. 
    * If you have not yet identified both a quantitative, a binary, and a categorical variable that you are interested in, now is the time to go back to the codebook and figure this out. 
II. Recode variables as needed. 
    * If your response variable is categorical with many levels, you may want to collapse it down to fewer than 5 levels. 
    * It is perfectly acceptable to recode variables temporarily for exploratory purposes and not put it in your data management file.


# Instructions

For each bivariate relationship under consideration you will do the following: 
  
1. Create the appropriate graphic for bivariate relationship under consideration. For these plots binary variables are treated as categorical variables with only 2 levels. 
    * C ~ C: Side by side barplot
    * Q ~ C: Paneled histogram with density overlaid, or a grouped boxplot with overlaid violin plot. 
    * Q ~ Q: Scatterplot. Add both lowess and linear trend lines.

2. Calculate appropriate grouped summary statistics
    * For continuous outcomes you'll want to describe measures including the sample size, mean, median, range and variance for each level of the categorical variable. 
    * For categorical outcomes you'll want to calculate %'s of your outcome measurement across levels of your covariate. 
        - i.e. proportion of males who are smokers compared to proportion of females who are smokers
        - or proportion of smokers who are male, compared to proportion of non-smokers who are male. 

3. Explain the relationship or trends you see in the data in a summary paragraph. Put this paragraph below the graphic. 
    * Use summary statistics in your text explanation. 
    * Use specific features of the graphic in your text explanation.
        - i.e. are there outliers only in one group?
        - Do the data seem clumped or clustered in one region of the scatterplot? 
        - Is there a linear or non-linear pattern? 
        - Does one combination of categorical levels (C~C) seem to hold most the data? 
        - Are there any outlying data points? Don't list off each one, just state if there is and where approximately it's at. 

## Example

```{r, fig.width=5, fig.height=3, fig.align='center', warning=FALSE, message=FALSE}
library(tidyverse); library(knitr)
iris %>% group_by(Species) %>% 
         summarise(mean=mean(Petal.Length), 
                   sd=sd(Petal.Length), 
                   n=n()) %>% 
         kable(digits=2)

ggplot(iris, aes(x=Species, y=Petal.Length, fill=Species)) + 
  geom_boxplot(width=.4) + geom_violin(alpha=.3) + 
  stat_summary(fun.y="mean", geom="point", size=3, pch=17, 
    position=position_dodge(width=0.75)) + theme_bw()
```

With equal sample sizes across the three iris species, there is clear difference in the average Petal length across the pecies. _Setosa_ has an average petal length of 1.5 (sd 0.17), _Veriscolor_ has an average petal length of 4.3 (sd 0.50), and _Virginica_ has the largest average petal length of 5.6 (sd 0.55). 


