---
title: "Regression Assignment"
author: "Robin Donatello"
date: "Last Updated `r Sys.time()`"
output:
  pdf_document: default
  html_document:
    highlight: tango
    theme: flatly
    toc: yes
    toc_float: yes
css: ../css/customh5.css
---

# Assignment Overview

You will perform <span style="color:blue">3</span> regression analyses in this assignment. For each you will interpret the regression coefficients, and test for a potential confounder $Z$.

1. Multiple Linear Regression: $Q \sim X + Z$
    - For this assignment choose a quantitative $X$ and a binary confounder $Z$, where the bivariate $Q \sim Q$ relationship is significant.
2. Logistic Regression: $logit(B) \sim X + Z$
    - Your binary response variable $Y$ must be coded as 1 (event) and 0 (non-event).
    - For this assignment, choose a binary $X$ and a binary confounder $Z$. 
3. Log-Linear Regression: $log(Q) \sim X + Z$
    - The explanatory variable $X$ can be binary or quantitative. 

4. Using one of the three above analyses (or a new model) add a third categorical (more than 2 levels) variable e.g.: $Q \sim Q + C$.

Worked out examples are available as [[HTML]](Regression_Assignment_Examples.html) or [[PDF]](Regression_Assignment_Examples.pdf)

# Instructions

0. Use the template provided: [[RMD]](Regression_template.Rmd) for R users, and [[Word]](Regression_template.docx) for SPSS users. 
1. Identify variables under consideration
    - Determine a third variable $Z$ that you want to test as a potential confounder.
    - Consider the relationship and ask yourself: "_If I had to predict a future persons response based on the Predictor/Explanatory variable and some other variable(s), what would they be?_"
    - <span style="color:red">For the purposes of this assignment your potential confounder $Z$ must be binary</span>. In reality, confounders, covariates, mediators, and moderators can come in all data types. 
2. Write out the null, alternative, and confounder Hypotheses statements.
    - **Null** - that there is no relationship between response and explanatory variables
    - **Alternative** - that there is a relationship between response and explanatory variables. 
    - **Confounder** - that there is a relationship between response and explanatory variables after controlling for the confounding variable. 
3. Fit the simple model
    - Model the response variable on the explanatory variable `y ~ x`
    - Determine if you are going to reject the null in favor of the alternative.
4. Fit the multivariable model. 
    - Only do this if you rejected the null.
    - Model the response variable on the explanatory variable and the third variable. `y ~ x + z`
    - Determine if $Z$ is a confounder by looking at the p-value for the explanatory variable. 
        - If it is still significant, the third variable **is not** a confounding variable. 
        - If it is no longer significant, the third variable **is** a confounding variable. This means that the third variable is explaining the relationship between the explanatory variable and the response variable.
5. Interpret all regression coefficients except the intercept. 
6. Write a conclusion. A structured response template is provided. 


