---
title: "Univariate Descriptions"
output:
  html_document:
    highlight: tango
    theme: flatly
css: ../css/customh5.css
---

There are a variety of conventional ways to visualize data - tables, histograms, bar graphs, etc. Now that your data have been managed, it is time to graph your variables one at a time and examine both center and spread. You will follow up each graphic with a table of summary statistics (for quantitative variables) or frequency and proportion table (for categorical), and then a summary paragraph that brings it all together. 

So you display the code, a graph, then a table, then words to describe that distribution. Then the code a graph, a table, paragraph etc. **Display of code is for this assignment only**
Because you know that to fully understand what is going on you need Twenty-seven 8 x 10 colored glossy photographs with circles and arrows and a paragraph on the back of each one explainin' what each one was. Or something like that (brownie points if you get the reference).

 
## Instructions

1. Go through your variables and make sure that you know what variables are categorical and what are quantitative.
2. Completely describe at least 2 of your categorical variables. 
    - Be sure to apply appropriate titles and axes labels 
3. Complete describe at least 2 of your quantitative variables. 
    - If you DO NOT have truly quantitative variables, then consider if the quantitative variable age or some other quantitative variable(s) would be a variable(s) to include. If not, then you need to do additional categorical variables to bring the total variables described to 4.



### To write a short description of this graph ask yourself (and answer!) the following questions:
1. What is the trend in the data? What exactly does the chart show? (Use the chart title to help you answer this question)
2. What are the axes and what are the units?
3. Describe the shape:
    - Symmetry/Skewness - Is it symmetric, skewed right, or skewed left?
    - Modality - Is it uniform, unimodal, or bimodal?             
4. Describe the spread:
    - Variability - What is the approximate range of the data (x-axis)?
    - Does the variable have a lot of variability in the data (visually, are the participants responded to many different responses or mainly just one)?
5. Describe the center: What is the approximate mean/median/midpoint of the data? (Pick one or two). 
6. Describe the outliers (note: there may not be any for every graph):
    - Are there any outliers for the variable?
    - If yes, are these true outliers or false (due to data management or input error) outliers?


## Export your results
* WORD for SPSS users, HTML for R users. 
    - SPSS users - paste your code for each graphic directly before that graph.
    - R users - don't hide your code chunks. 
* Any data management done should be shown at the very top of your report. 
* Upload this document as a blog post. Write a short summary paragraph in the body of the post letting the reader know what this post is about and what variables you looked at. 
