---
title: 'Week 2: 8/28 - 9/1'
date: "Last Updated `r Sys.time()`"
output:
  html_document:
    highlight: tango
    theme: flatly
    toc: yes
    toc_float: yes
css: css/customh5.css
---

```{r,echo=FALSE, warning=FALSE, message=FALSE}
library(knitr)
#library(rmarkdown)
opts_chunk$set(warning=FALSE, message=FALSE) 
```

##### New Assignments (on week 1 content)
I finally figured out how I'm going to have to grade blog posts & peer reviews (Manually basically). 

* I have shared with you all a MATH 615 folder in Google Drive. 
    - In this folder there is a spreadsheet called "Peer Review Rotation". 
    - This shows you for each peer review assignment, who your assigned reviewee's are. 
    - The student names that are listed, are the ones YOU will be reviewing. Each person reviews two classmates posts. 
* A review consists of providing 1 positive comment, and 1 thing they can do better or a suggestion (One up, One down)
* Your first peer review assignment is on the research question / personal codebook blog post (The one that was due 8/28). 
* All of this is also listed on the Project page (from the nav bar).

# Tuesday: Data Import & Preparation
Goals: 

* Be able to import different data types into your software program of choice (SPC)
* Learn how to identify mistakes and missing data in data using tables and summaries
* Learn how to correct certain mistakes
* Learn how to recode variables into new ones

## Prepare
* Read the questions to ask yourself to prepare for data management. [[HTML]](docs/dm_prep_qs.html) or [[PDF]](docs/dm_prep_qs.pdf) 
* Read the `depression` data set into your SPC (See below for help importing data.)
* Review the notes on doing [[data management]](http://www.norcalbiostat.com/lec/lec_doing_dm.html)
    - Start to replicate the code concepts in these notes in your SPC. 

## In Class

* Data management and cleaning in a reproducible manner. 
    - This will be done in a single script file that imports the data, does cleaning, and saves the cleaned data set with a new name. 
    - R users will create a new `depression_dm.RMD` file. 
    - SPSS users should create a new `depression_dm.txt` file. Windows uses Notepad, Mac uses TextEdit.
* Walk through the data management process on the depression data set.     
    - Recording all steps in script file 
    - Export analysis data set. Save script file. 
* Start a `add_health_dm.Rmd` or `add_health_dm.txt` file for Add Health. 


## Resources
* R (Data Import)
    - https://norcalbiostat.github.io/MATH130/materials/day3-import-and-factors.html 
    - http://dwoll.de/rexrepos/posts/dfImportExport.html 
    - https://www.datacamp.com/community/blog/an-introduction-to-cleaning-data-in-r#gs.7=03Hnc 
* R (Data Preparation)
    - http://dwoll.de/rexrepos/rerR_Basics.html 
    - https://stats.idre.ucla.edu/r/modules/ 
    - https://www.datacamp.com/community/blog/an-introduction-to-cleaning-data-in-r#gs.7=03Hnc 
* SPSS (Data Import)
    - https://www.ibm.com/support/knowledgecenter/en/SSLVMB_22.0.0/com.ibm.spss.statistics.help/spss/base/datafile_auto_0.htm
    - http://libguides.library.kent.edu/SPSS/ImportData
* SPSS (Data Preparation)
    - https://www.ibm.com/support/knowledgecenter/en/SSLVMB_22.0.0/com.ibm.spss.statistics.help/spss/base/data_prep.htm 
    - https://stats.idre.ucla.edu/spss/modules/


##### Assignments
* Blog about some issues you are going to have to deal with during data management. 
    - Name variables specifically. 
    - Check a few of your classmates blogs about this. Chances are you will be doing similar approaches to handling data on different variables. 
    - Use the [data management](docs/dm_prep_qs.html) preparation questions as a guide for your thoughts. 
    - This is **not** about learning syntax, or the program, or other logistics
    - You are asking yourself "what am I going to have to DO to the data to put it in a form where I can answer my research question."
    
* Peer review (one up one down) two assigned classmates' blog posts about their recoding and data management woes. 
* Start a data management file for the Add Health data. You wil submit this to BBLearn by the due date. 
    - This must be a single script file that imports the data, does cleaning, and saves the cleaned data set with a new name. 
    - It should have sections in it that reflect the overarching types of data management to be done 
        - i.e. subsetting, addressing missing, recoding, making secondary variables etc. 
    - It does not have to be comprehensive or finished by the due date! Likely it will not be. 
        - I just want to make sure you are getting started in a reproducible manner in a reasonable time. 
    - R users should upload a `.RMD` file. 
    - SPSS users should upload a `.txt` file. Windows uses Notepad, Mac uses TextEdit. 
        
    
----

# Thursday: Literature Review & Citation Assignment

## Prepare
* Read: [How to read a Journal Article](docs/How to Read a Journal Article.pdf)
* Read: Literature review notes [[HTML]](http://www.norcalbiostat.com/lec/lec_lit_review.html)

## In class
* Brief discussion of literature review & citation assignment. 
* Work on on your own: Citation Assignment _or_ continue data management. 


##### Assignments

* Citation assignment Instructions [[HTML]](hw/Citation_Assignment.html) [[PDF]](hw/Citation_Assignment.pdf) 
    - [Example submission](docs/Citation Assignment Example.pdf)



