---
title: "Introduction to MATH 615"
date: "Last Updated `r Sys.time()`"
output:
  html_document:
    highlight: tango
    theme: flatly
    toc: yes
    toc_float: yes
css: ../css/customh5.css
---

# Navigating course resources
* My website: http://norcalbiostat.com
    - First stop for all class materials
    - Links to individual classes, but shared resources on programming and data. 
* This class website https://norcalbiostat.github.io/MATH615/ 
    - Landing page for announcements
    - Details on weekly topics can be found on the schedule
    - Includes links to notes and additional materials
    - Sometimes links will not make it to all places (schedule/weekly overview/notes).
* Often links will be broken. Typo's happen. Notify me immediately and I'll get to it asap. 
* Both are mobile friendly to different extents. 
* The syllabus covers course details such as grading, office hours and required materials. 
* Blackboard Learn (BBL) used for discussion boards, blogging, and assignment submission. 
* Textbook used for data, reading and learning content. Sometimes problem sets. 


# Descriptive vs. Inferential Statistics
* [Passion Driven Statistics](PDS_Intro_Stat.pdf)
* Google `data analysis lifecycle` and look at images. What sense do you get? 


# Computing and Reproducibility
* Review these [Slides](http://benmarwick.github.io/UW-eScience-reproducibility-social-sciences/#/) on reproducible research in the social sciences.
    - I will not require any measure of version control or open source coding in this class. 
    - However nearly 80% of my work is available online. 
    - Big push for open research in the Natural Sciences. 
* Be mindful about file naming conventions (slide 11). Make a plan and stick with it. 
    * https://www.xkcd.com/1459/
* Expect to bring your laptop every day to class. 
    - The more reading and content learning done outside of class, the more time for in class analysis and discussion
    

# Analysis software choices    
* I will not dictate which software program you use in this class. 
* All my lecture notes use R. This entire website is built with R. That does not mean you must use R. 


## R
* Free. 
* Coding from day 1. Harder up front, more powerful in the end. 
* Seamless integration with a multitude of other scientific analysis and reporting mechanisms. 
* Google `tidyverse` images. Compare it to the images of the data analysis life cycle. What sense do you get? 
* My [instructions](https://norcalbiostat.netlify.com/post/software-overview/) on how to get setup.
* On campus resources
    - Introduction to R (MATH 130) 1 unit CR/NC
    - Data Science Initiative workshops, talks, open drop in analysis time. 
* Off Campus resources (a few)
    - Chico R Users Group 
        - [Meetup](https://www.meetup.com/Chico-R-Users-Group/)
        - [Google l-serv](https://groups.google.com/forum/#!forum/chico-rug)
    - [Data camp](http://www.datacamp.com)
    - [Quick-R](http://www.statmethods.net/)
    - [Cookbook for R](http://www.cookbook-r.com/)
    - [R Examples Repository](http://dwoll.de/rexrepos/) (This site was also built using R Markdown, is open source and a fabulous example of reproducible research!)
   
   
## SPSS
* [Purchase v23 or v24](http://www-03.ibm.com/software/products/en/spss-stats-gradpack) for $50 for 6mo rental. 
* Point and click, but can save code and write scripts. 
* Stand alone program. No integration. 
* Will be used again in NSFC 600 (no exp necc for that class either)
* On campus resources: From the desk of David Philhour (BSS) 
    - Open computer labs in Butte Hall (207, 211) with many open lab hours.
    - Tutoring center in AJH108 run by Dr. Penelope Kuhn. 
    - The psyc depth lab is Modoc 224 but is pretty impacted with classes Monday thru Thursday. Friday's are pretty open.
* Off Campus resources
    - Recommended [YouTube videos](https://www.youtube.com/results?search_query=andy+field+spss+tutorials) 
    - [UCLA IDRE PMA5 textbook examples](https://stats.idre.ucla.edu/other/examples/pma5/)

## SAS? STATA?
* If you have a burning desire to sure. I'm proficient in both. 
* AFAIK SAS is only now working on literate and integrated programming by using Jupyter notebooks and SAS University Edition (free)
* UCLA IDRE also has PMA5 textbook examples. 

# Going Public
* You're going to be doing an analysis on a public data set. 
* We're talking reproducibility and open source, let's put theory to practice. 
* You will "publicly" share your analysis steps and thought process. 
    - "Public" is in quotes because it will only be public to our class using Blackboard Learn
    - For those gung-ho R users I *highly* recommend building your blog using [`blogdown`](https://bookdown.org/yihui/blogdown/). 
        - This is the [tutorial](https://apreshill.rbind.io/post/up-and-running-with-blogdown/) that I used to get going.
        - Easy for even a moderate experienced R user to do. I can help you with setup if you need.


## Blogging in Academica

Taken directly from the `blogdown` documentation by Yihui Xie: 

> In the summer of 2012, I did my internship at the AT&T Labs Research,1 where I attended a talk given by Carlos Scheidegger (https://cscheid.net), and Carlos said something along the lines “if you don’t have a website nowadays, you don’t exist.” Later I paraphrased it as:

> “I web, therefore I am a spiderman.”

> Carlos’s words resonated very well with me, although they were a little exaggerative. A well designed and maintained website can be extremely helpful for other people to know you, and you do not need to wait for suitable chances at conferences or other occasions to introduce yourself in person to other people. On the other hand, a website is also highly useful for yourself to keep track of what you have done and thought. Sometimes you may go back to a certain old post of yours to relearn the tricks or methods you once mastered in the past but have forgotten.


Here are some other recently googled blog posts about why academics (and grad students) should blog  

* http://www.teaching-matters-blog.ed.ac.uk/?p=1685
* http://www.megankatenelson.com/4-reasons-blogs-are-great-for-academia/
* https://www.timeshighereducation.com/blog/seven-reasons-why-blogging-can-make-you-better-academic-writer


